### ISSUE TITLE
Working Group members Management and other requirements

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist#144]
- [x] Do not allow creating a proposal if you are not a member of the WG
- [x] Fix the list of pending requests and approvals on a WG, must be visible to coordinators and members 
- [x] Make sure the role EXPERTS is available when adding
- [x] Rename the role EXPERTS as JURY in the UI
- [x] Write script to add proposals from a theme to a WG
- [x] Script to archive all the proposals from phase 1 when it finishes
- [x] Make sure ARCHIVED proposals show the same as EXCLUDED
- [x] Add filter to show only ARCHIVED
- [x] Fix the comment on WG page
- [x] Hide email of members from public view
- [x] Add ARCHIVED to status options on the proposal page
- [x] Add to Working Group button on menu of proposal/idea cards: it should show you the list of your WGs so that you select one to add that proposal to
- [x] Hide Assigned Ideas
- [x] Hide idle buttons: join, subscribe, join 2 from anonymous view
- [x] Change "Join the Group to create proposals" to "Login to join"
