### ISSUE TITLE
PeerDoc Fork & Merges + Other Phase 3 Requirements 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist#148]
Implement an interface to PeerDoc's Fork and Merges 
https://docs.google.com/document/d/1CkIr9d8yvYJ3f8Hl0rV8fTfrkSJ85LfVdvg7jsJF9iE/edit

## Notes
- [x] Some considerations. Verify and check the ones already supported:
	- [ ] All authors (creators and shared-with) of initial proposals will be registered with the WG associated with the theme of their proposal as proposals are added to the WGs via script.
	- [ ] Anyone in the Unifesp community can request to join a WG.
	    - [ ] By request:
	          * Sign in into AppCivist
	          * Visit the Working Group Page
	          * Click the join working group button
	          * Wait for a coordinator to approve your membership request
	    - [ ] Added by coordinators: 
	          * Coordinators go to the WG they manage and upload a list of members (name, email, role) in a csv.
	 
	- [X] Same permission scheme as with Initial Proposals
	- [ ]  Add configuration to hide private drafts in WG page from non-authors.  
	- [ ]  Add filters in WG page to show 'my proposals', 'draft proposals', 'shared with me'. 
	- [ ]  Button to start proposal from WG page that behaves the same as in campaign page
	- [ ] Send/View notifications when new authors are added in AppCivist to a proposal I created, was shared-with or follow 
	- [ ] Send/View notifications when changes are made in AppCivist to a proposal I created, was shared-with or follow
	- [ ] Somebody decides to make a fork.

## Backend TODO: 

- [ ] AC Back: Add statuses for forked proposals in AppCivist: FORKED_PRIVATE_DRAFT, FORKED_PUBLIC_DRAFT, FORKED_PUBLISHED
- [ ] AC Back: Add statuses for merged proposals in AppCivist: MERGED_PRIVATE_DRAFT, MERGED_PUBLIC_DRAFT
- [ ] AC Back: Add statuses translations for new statuses
	1. FORKED_PRIVATE_DRAFT => "Private Draft Ammendment"
	2. FORKED_PUBLIC_DRAFT => "Public Draft Ammendment" 
	3. FORKED_PUBLISHED => "Published Unmerged Ammendment"
	4. MERGED_PRIVATE_DRAFT => "Merged Private Ammendment"
	5. MERGED_PUBLIC_DRAFT => "Merged Public Ammendment"
	6. [if we include REJECT] REJECTED_PRIVATE_DRAFT => "Rejected Private Draft Ammendment"
	7. [if we include REJECT] REJECTED_PUBLIC_DRAFT => "Rejected Public Draft Ammendment"
	8. [if we include REJECT] REJECTED_PUBLISHED => "Rejected Published Ammendment"
- [ ] AC Back: Extend Contribution model with attribute `parent_id` of type Long to point to parent proposal
- [ ] AC Back: POST /api/proposal/:pid/proposal forks the proposal `pid` and communicates to PD to fork the associated PeerDoc. 
		0. First, ask PD to fork PeerDoc document associated with the proposal `pid`
		1. If PD communication is a success, fork the proposal in AppCivist
		2. Forking means duplicating the original proposal (i.e., the parent) into a new proposal (i.e., fork) having `fork.parent_id` = `parent.contribution_id`
		3. Add the forked PD url to the newly created Fork `extendedTextPad` property 
		4. Initialize the status of the fork with FORKED_PRIVATE_DRAFT
		5. Status changes rules are the same as in private/public/published, but always using FORKED_ statuses  
		6. After successfully duplicating the proposal and attaching the new PD fork url, add the fork to the WG's and Campaign's resource space of the parent
		7. Notify the creator, shared with users and followers of the parent resource space that a fork was created
		8. For 7 to work, create a new type of event for the notification signals. 
		9. *PERMISSIONS REQUIRED FOR THIS:* any working group member can FORK proposals in the WG. 
- [ ] AC Back: PUT /api/proposal/:pid/proposal/:pid?merge=true to merge a fork onto its parent
		0. First, ask PD to merge the fork PD into the parent PD. 
		1. If PD responds with success, change status if fork from FORK_x to MERGED_x (if x is PUBLISHED, use PUBLIC_DRAFT in the MERGED status) 
		2. Notify creator, authors and followers
		3. Create new event signal type to notify users
		4. *PERMISSIONS REQUIRED FOR THIS:* only available to the parent creator and authors
- [ ] AC Back: update permissions controls to replicate permissions for FORKED_* statuses
- [ ] AC Back: implement permissions controls to ensure MERGED_* statuses are frozen (cannot change anything else by anyone, except ADMINS. Do not include COORDINATORS)
- [ ] AC Back: apply same requirement controls when passing from one status to the other for update permissions control to replicate permissions for FORKED_* and MERGED_* statuses
- [ ] AC Back: GET /api/proposal/:pid/proposal?type=[forks|merges|parent] Responds with the list of children (forks or merges) or the parent of a proposal `pid`
		0. If a fork is PRIVATE, include it only if the user who requested this is COORDINATOR, creator or author of parent.
- [ ] AC Back: GET /api/public/proposal/:pid/proposal?type=[forks|merges|parent] Responds with the list of children (forks or merges) or the parent of a proposal `pid`
		0. Include only PUBLIC or PUBLISHED forks and merges
- [ ] #LowPriority (this must be done in PEERDOC) Send/View notifications when changes are made in PeerDoc to a proposal I created, was shared-with or follow

### Additions to all proposals page: 

- [ ] AC Front: Fork button "Create amendment" (fork) that communicates to the API that a fork is created from this proposal
	1. Should open a confirmation modal before issuing the call. 
	2. After creating the fork, redirect to the proposal page of the fork
- [ ] AC Front: If proposal is a "fork" (i.e., has a parent + status start with FORKED_, add a button in toolbar “Parent proposal” 
	1. Open a modal showing the title of the parent proposal and a button to visit the parent proposal page 
- [ ] AC Front: If proposal is a parent (i.e., has forks and merges), add button “Amendments” (Forks) that if pressed, shows the list of forks 
	1. Link each fork/merge to its proposal page
	2. Show each fork/merge status 
	3. This can be seen in a modal window or simply showing the list of forks somewhere in the page.
	4. Only visible to authors of the proposal and COORDINATORS 
- [ ] AC Front: If proposal is a fork and user is creator or author of the parent, add a button to “Merge” 
	1. visible to the authors of the parent proposal 

### Additions to all campaign and WG page: 

- [ ] AC Front: Badges for new statuses on the proposal cards, using properly translated versions (provided by James)
- [ ] AC Front: add all the new statuses for fork and merges
- [ ] AC Front: Public merges are treated as public drafts (they are shown under the filter for public proposals)
- [ ] AC Front: Private merges are treated as private drafts (they are shown under `My proposals`, `Share with me` and `Draft proposals` in the case of coordinators).
