### ISSUE TITLE
Docker cleanup

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist#149]
- [x] Local development docker compose version
- [x] Initial data updated to include newest developments and models
- [x] Documentation on how to edit the initial data yml to initialize an instance. We should find a way to easily make possible to incorporate all the information that is displayed in this seed document (maybe we can make the YML easily editable online for non-tech users): https://docs.google.com/document/d/1e5iS3TpmrHNlBaCA26YtoYowZtdKjrns-SBssyEKV2E/edit?usp=sharing
- [x] Fix/support UNIFESP tech team so that they can finally install and maintain their local versions and know how to deploy if needed. 
Some of the issues are listed here: https://docs.google.com/document/d/1Aat-xk2aZMKjs-E503-FVs9LnlcnZ4xz60Gdq8t0RU8/edit

**Comment by mitar** [comment]
Closing this for now. We are now working only on a small subset of issues.
