### ISSUE TITLE
Nouvelle Aquitaine Requests

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist#2]
cc @LucileMP 
Just to keep NA on the loop, we are currently working in the following issues related to NA requests: 

- [ ]  [Fix encoding issue with Etherpad](https://github.com/socialappslab/appcivist-platform/issues/417)
- [X] [Implement basic edit campaign page so that NA people can update information of the timeline themselves](https://github.com/socialappslab/appcivist-pb-client/issues/196)
- [X] [Implement basic edit working group page so that NA people can update information of the WG themselves](https://github.com/socialappslab/appcivist-pb-client/issues/577)
- [X] [Add proposal button in WG page](https://github.com/socialappslab/appcivist-pb-client/issues/595)
- [x] [Hide some fields from the contribution and the feedback form](https://github.com/socialappslab/appcivist-pb-client/issues/594)

**Comment by cdparra** [comment]
Except for the first item, everything else is done. Will create another issue to track the problem with etherpad encoding. cc @LucileMP
