### ISSUE TITLE
Issues with PeerDoc embedding

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist#73]
* [x] It seems embedding URL does not include `embed=true` query string parameter, so toolbar is shown. We do not want a toolbar when embedding.
* [x] For best UI, use the following style of the iframe: `style="width: 100%; border: 0;" frameborder="0" scrolling="no"`
* [x] AppCivist does not resize the iframe when content resizes. See JavaScript code below which resizes an iframe when AppCivist receives a message with content size. PeerDoc is sending such messages if `embed=true` is set.
* [x] When I first created a proposal and clicked "PeerDoc" button for content, PeerDoc was loaded without user token. I had to reload the page for token to be sent. Ideally, this should not be needed.

This is an example how to embed PeerDoc:

```
<html>
  <body>
    <p>Before.</p>
    <iframe src="http://localhost:3000/document/kZuiP9q3oKzZdCaya?embed=true" style="width: 100%; border: 0;" frameborder="0" scrolling="no"></iframe>
    <p>After.</p>
    <script>
      window.addEventListener('message', function (event) {
        if (event.data.size) {
          Array.prototype.forEach.call(document.getElementsByTagName('iframe'), function (element) {
            if (element.contentWindow === event.source) {
              element.style.height = `${event.data.size.height}px`;
            }
          });
        }
      }, false);
    </script>
  </body>
</html>
```

**Comment by cdparra** [comment]
Does the last of the 4 issues still hold?
