### ISSUE TITLE
Campaign page modifications

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#75]
Attached is mockup of Campaign Page with a few modifications:
1.  Each phase will now show an instruction alert linked to it. The attachment below shows alert for Fase 1 (with vertical line to Propostas Iniciais).
2.  Change button text [Adicionar Proposta] to [Criar Proposta].
3.  Add "? FAQ" to right of "Temas e Palavras-chave" (will supply FAQ text/animation later)
4.  Put Desenvolvido por AppCivist (tool bar) on one line.
5.  Add a button [Video PPI] in center of top header and link to video https://drive.google.com/open?id=1VoUN4tszhHHXIASGU-wWBuMbG2JM4R9F

6.  Re-order themes in "Temas e Palavras-chave" window as follows:
Visão de Universidade / Universidade Pública e Direito à Educação / O Estudante Universitário no Sécula XXI / Universidade, Território e Sociedade / Universidade Crítica, Ética e Inovadora / Ensino-Aprendizagem / Formação de Educadores / Avaliação / Redes de Colaboração Nacionais e Internacionais / Gestão Acadêmica e Estruturas Organizacionais 

![campaign page mockup 2018-04-12](https://user-images.githubusercontent.com/5572598/38755820-89f4aaf2-3f3d-11e8-99ba-58b9f3ae650d.png)

**Comment by cdparra** [comment]
-[ ] For (1), put desired phrase to show in the phase description. The UI will read from there to show in this element and show it in a box with border connected by a line to the text and with content centered.  
- [ ] (2) Replace with create proposal
- [ ] (3) Add configuration of FAQ URL
- [ ] (4) Increase width of "powered by"...
- [ ] (5) 
     - [ ] 5.1 Add video to youtube (this is assigned to @Alissonor) 
     - [ ] 5.2 then add it as one of the medias in the campaign (assigned to @cdparra)
     - [ ] 5.3 embed in the saiba mais page (assigned to Eduardo)
     - [ ] 5.4 James to think about best translation of midia (option is Videos and Images)
- [ ] (6) @cdparra to play with database to see how this can be reordered because it depends on the order of creation.
